apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubenexus.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubenexus.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.backend.env.APP_ENV | quote }}
  APP_PORT: {{ .Values.backend.env.APP_PORT | quote }}
  SERVER_PORT: {{ .Values.backend.service.port | quote }}
  K8S_IN_CLUSTER: {{ .Values.backend.env.K8S_IN_CLUSTER | quote }}
  DB_HOST: {{ include "kubenexus.dbHost" . | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  DB_USER: {{ .Values.database.user | quote }}
  DB_SSLMODE: {{ .Values.database.sslmode | quote }}
  REDIS_HOST: {{ include "kubenexus.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  JWT_ACCESS_DURATION: {{ .Values.jwt.accessDuration | quote }}
  JWT_REFRESH_DURATION: {{ .Values.jwt.refreshDuration | quote }}
