apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubenexus.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubenexus.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc | quote }}
